services:
  frontend:
    build:
      context: ./Tresor
      dockerfile: tresor.web.frontend.Dockerfile.dev
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./Tresor/tresor-web:/app
      - /app/node_modules
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true


